### ISSUE TITLE
change event will return all supported formats - bug

### ISSUE THREAD

**Issue by vonec** [xxRockOnxx/vuejs-timepicker#19]
"Unlike v-model, which only returns the defined time tokens you provided in the binding variable, the change event will return all supported formats."

@change event is not firing

@blur is working but return only HH:mm contradictory to the above doc am i missing something

**Comment by vonec** [comment]
Blur or change doesn't matter .. i just posted since it's not documented ... Thank for maintaining this repo... I'm building a simple from - to fields and so thif the first fields value is 10:00 then all the best less than or equal to 10am must be un selectable .. bumping intha index of issues now ... Any example ?

**Comment by xxRockOnxx** [comment]
That has been asked before but sadly the person did not continue making a PR for it: #6 

I just don't have the time to make a new feature unfortunately. Easiest thing you can do is thru validation. A more hacky one is add ` ref` on the timepicker then loop over the elements you dont want and hide them.

**Comment by vonec** [comment]
disabledValues is this not functional?

**Comment by vonec** [comment]
` <vue-timepicker 
    v-model="from"
    :minute-interval="15"
    @blur="updateTo($event, 'foo')"
  ></vue-timepicker>
  <vue-timepicker 
    v-model="to"
    :minute-interval="15" 
    :disabled="isDisabled"
  ></vue-timepicker>`

and 

`
      updateTo (eventData, arg) {
        console.log(eventData)
        console.log(arg)
        console.log('-----')
        this.isDisabled = false
        // -> {data: {HH:..., mm:... }}
      }`

**Comment by vonec** [comment]
> <vue-timepicker 
    v-model="from"
    :minute-interval="15"
    @blur="updateTo($event, 'foo')"
  ></vue-timepicker>>
  <vue-timepicker 
    v-model="to"
    :minute-interval="15" 
    :disabled="isDisabled"
    :disabledValues="disabledValues"
  ></vue-timepicker>> 

      updateTo (eventData, arg) {
        console.log(eventData)
        console.log(arg)
        console.log('-----')
        this.isDisabled = false
// loop here  -- 
// 1. the format is HH so i have you parseInt 
// here and the following line thows "TypeError: Cannot read property 'indexOf' of undefined"
        this.disabledValues = { hours: [4,5,6], minute: [], second: [], apm: []}
     }
--



        // -> {data: {HH:..., mm:... }}
      }

**Comment by vonec** [comment]
+        <li
+          v-for="hr in hours"
+          v-text="hr"
+          v-show="disabledValues.hour.indexOf(hr) === -1"
+          :class="{active: hour === hr}"
+          @click.stop="select('hour', hr)"></li>

something wrong with that ?

**Comment by xxRockOnxx** [comment]
Can you try `hour` instead of `hours`? I might have some spelling mistakes on the README

**Comment by vonec** [comment]
doing few changes and there needs to documentation about events @input @blur

**Comment by danielvancamp** [comment]
Just tried this myself and it seems you should parse the **hr** to an integer to get it to work. Guess it would be the same for minute, seconds and apm.
 
`<li v-for="hr in hours" v-text="hr" v-show="disabledValues.hour.indexOf(parseInt(hr)) === -1" :class="{active: hour === hr}" @click.stop="select('hour', hr)"></li>`
