### ISSUE TITLE
[feature/question] More than 24 hours when in 24 hour format

### ISSUE THREAD

**Issue by brodul** [xxRockOnxx/vuejs-timepicker#21]
I have to represent a duration of a process that can take more that 24 hours.

I would like to use vue2-timepicker, but the max hours the user can select in 24 mode is 23.
Would you accept a PR that adds a prop that changes the hour count to more than 23 hours if in 24 hour mode?

**Comment by xxRockOnxx** [comment]
check the table on `README` there's 01 - 24 format

**Comment by brodul** [comment]
Can I open a PR to extend to more that 24 hours?

**Comment by xxRockOnxx** [comment]
What's your use case and proposal for it?

**Comment by xxRockOnxx** [comment]
What's your proposal for it?

Also, how do you use timepicker for duration purpose? I mean, isn't a single input with number that represents hours not enough? Something like `[ x ] hours from [XX]:[XX]`

**Comment by xxRockOnxx** [comment]
Will close this in 24hrs if OP didn't reply.

**Comment by brodul** [comment]
I will probably write a separate component for this (spec are changing).

Thank you for your time :beer:
