### ISSUE TITLE
Emit open and closed events

### ISSUE THREAD

**Issue by AnwarElbo** [xxRockOnxx/vuejs-timepicker#23]
Change event is triggered far too often, I need to do an AJAX request whenever the time is updated. In the old repo there was already a pull request could you also merge it in this repo? 
See: https://github.com/phoenixwong/vue2-timepicker/pull/14

**Comment by xxRockOnxx** [comment]
I was about to do it but seems like I have a `blur` event set that you might be able to use.

https://github.com/xxRockOnxx/vuejs-timepicker/blob/master/src/vue-timepicker.vue#L202

Can you try it for me? I just got back from being sick.

**Comment by xxRockOnxx** [comment]
All is good for now I guess. It's the documentation that really needs to be worked on. Looking forward to do that very soon. It's very messy.
