### ISSUE TITLE
Request for UMD module to use directly in browser

### ISSUE THREAD

**Issue by cksachdev** [xxRockOnxx/vuejs-timepicker#24]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What are the steps to reproduce the bug?
1. Create a simple vue app using js library from cdn
2. Include vue-timepicker using script tag
3. Include css for vue-timepicker
4. Run the page

Expected result:
Vue timepicker should work 

Actual result:
Throws an error

**Comment by mattjhosking** [comment]
Me too.
