### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by pepf** [xxRockOnxx/vuejs-timepicker#4]
One thing I wanted to work on in my own fork is keyboard support. being able to quickly select the right numbers by typing as well as clicking makes the component way more user friendly.

**Comment by xxRockOnxx** [comment]
The component uses `<ul>` instead of `<select>` which can natively detect keyboard inputs.

Currently don't have time to refactor that cause that might break something and/or the appearance. I can accept PRs though.

**Comment by salvatorious** [comment]
+1 for keyboard support, it would be really useful.

If you give some direction I could potentially refactor to use `<select>` and submit a PR.

**Comment by xxRockOnxx** [comment]
@salvatorious you can try look at the source. it's pretty simple actually. I'll try to do it also since it's look like  I'm free for a day or two.

**Comment by xxRockOnxx** [comment]
Update: doing select will only open 1 option at a time compared to the current one which can open everything at once since it is just a div. If that's fine then `<select>` refactor is a lot easier.
