### ISSUE TITLE
Custom hour Interval

### ISSUE THREAD

**Issue by SergioReis97** [xxRockOnxx/vuejs-timepicker#6]
Thanks for trying to keep the project up and running.
I was thinking about implementing something on the looks of a custom interval for hours minutes and seconds.

Interval steps work great but for example in my case i need only the normal working hours of a day (09 to 17 for example) and even if this meant having to specify all of them on an array.

Can try to do a PR soon if you find this intresting.

**Comment by xxRockOnxx** [comment]
there is already an interval prop. Maybe we can leverage that by passing a function instead of a number that returns the values? what do you think of that?

**Comment by SergioReis97** [comment]
Why not both? 
We can recieve the parameter as an array or as a function. If it is a function something similar to the minutes interval stepper, and if it's an array just use that.

**Comment by xxRockOnxx** [comment]
LOL was sleepy when I typed that. My initial thought was array would look tiring because you need to type everything. I just realized you can just generate it with a function... but you're idea is good.

Ok let's do it! Also, I thought of changing it to `minutes` because it'll not be an interval anymore. That's more precise.

**Comment by SergioReis97** [comment]
Hello, I tryed to pull the project and do the changes but i was unnable to even build the project as it was download. Not entirely sure why. Pulled the project, npm install, npm run dev and it runs BUT always throws [this](https://gyazo.com/34f0ee1b9041c5d10b8b3efca86251f4) error

**Comment by SergioReis97** [comment]
@xxRockOnxx check [this](https://github.com/SergioReis97/vue2-timepicker/commit/1d959199ef74f01a7f15c28d756452645e93c4f6) when possible please.. thanks.

**Comment by xxRockOnxx** [comment]
I will. Sorry I am busy maybe until next week with tons of heavy loads :\

**Comment by xxRockOnxx** [comment]
@SergioReis97 I looked at it and seems good. you might want to create a demo for it. I will try to fix the the building of demo files also.
