### ISSUE TITLE
Can you publish a new version to npm?

### ISSUE THREAD

**Issue by lichaozhy** [xxRockOnxx/vuejs-timepicker#8]
I guess you can NOT update this module with old name.

My suggestion is to re-publish the project with a new name. Inheriting the original signature and agreement in comment then we can do more useful things.

**Comment by xxRockOnxx** [comment]
yes sure. have any suggestion for the name?

**Comment by lichaozhy** [comment]
How about 'vue-timepicker-or' ?

**Comment by shershen08** [comment]
or `vue-timepicker-2` ? I would propose to choose anything asap and publish the npm package and also add it to the https://github.com/vuejs/awesome-vue/ because the master project is not maintained for around a year already.

**Comment by rhymes** [comment]
Any news on this?

Thank you!

**Comment by xxRockOnxx** [comment]
I think someone has to volunteer. I keep receiving my npm has been compromised on my gmail or something similar to that.

**Comment by rhymes** [comment]
@xxRockOnxx so maybe your credentials have been hacked last year: http://blog.npmjs.org/post/161515829950/credentials-resets - what if you reset your password ?

**Comment by xxRockOnxx** [comment]
@njwest yes go ahead. no problem with that.

**Comment by njwest** [comment]
Updating package.json now, want to add any emails/authors/etc? 

Are you Phoenix Wong?

**Comment by xxRockOnxx** [comment]
> How should we go about maintenance and refactoring to match the new package name? Rename the fork, move to a new repo keeping origins intact, or ?

hmmm, I'll go with just renaming the fork for now. Once there's a major change, then we can consider it a new package. I barely receive some bug reports this whole time actually that's why I haven't consider it a new package yet.
